version: "3"

services:
  database:
    image: postgres:15-alpine
    hostname: $${POSTGRES_HOST}
    container_name: smart_link_database
    environment:
      - POSTGRES_DB=database
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '8001:5432'
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    hostname: $${REDIS_HOST}
    container_name: shortener_cache_redis
    environment:
      - REDIS_HOST=redis
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '8002:6379'

volumes:
  database: