# Generated by Django 5.0.2 on 2024-02-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smarturl',
            unique_together={('full_url', 'short_url')},
        ),
    ]
