# Generated by Django 5.0.2 on 2024-02-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_smarturl_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smarturl',
            name='full_url',
            field=models.URLField(verbose_name='Полная ссылка'),
        ),
        migrations.AlterField(
            model_name='smarturl',
            name='short_url',
            field=models.CharField(db_index=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
